sudo: required
services:
  - docker
language: node_js

node_js:
  - 'node'

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: unit testing
      script: npm run test
    - stage: regression testing
      - script: bash deploy-dockerhub && npm run gemini:test
    - stage: deploy
      script: npm run build
      deploy:
        provider: script
        script: bash deploy-dockerhub && sh deploy-heroku 
        skip_cleanup: true
        on:
          branch: master