sudo: required
services:
  - docker
language: node_js

node_js:
  - 'node'

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: script
        script: bash deploy-dockerhub
        script: bash deploy-heroku 
        skip_cleanup: true
        on:
          branch: heroku-deploy