sudo: false
language: node_js

node_js:
  - 'node'

script:
  - npm run lint
  - npm run test

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: heroku
        app: collection
        api-key:
          secure: 8e20dd22-c8bf-4081-a595-0ca57498d763  
        skip_cleanup: true