dist: trusty
sudo: required
language: node_js

node_js:
  - 'node'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16"

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: unit testing
      script: npm run test
    - stage: regression testing
      script: bash gemini-selenium
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: heroku
        app: radiant-beach-82987
        api-key:
          secure: 293d7180-e627-4b81-ba29-65a762db2314  
        skip_cleanup: true