sudo: required
services:
  - docker
language: node_js

node_js:
  - 'lts/*'

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test && npm run gemini:test
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: script
        script: bash deploy-dockerhub && sh deploy-heroku 
        skip_cleanup: true
        on:
          branch: master