dist: trusty
sudo: required
language: node_js

node_js:
  - 'node'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: unit testing
      script: npm run test
    - stage: regression testing
      script: 
        - bash gemini-selenium
        - npm run gemini:test
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: heroku
        app: radiant-beach-82987
        api-key:
          secure: 293d7180-e627-4b81-ba29-65a762db2314  
        skip_cleanup: true